# Generated by Django 5.1.1 on 2025-06-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_job_freelancer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('job', 'Given_by')},
        ),
    ]
