# Generated by Django 5.1.1 on 2025-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
