# Generated by Django 5.1.1 on 2025-06-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='room_name',
        ),
        migrations.AddField(
            model_name='messages',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.job'),
        ),
    ]
